version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    command: pnpm start
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: node server.js
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
